### ISSUE TITLE
Install component failed

### ISSUE THREAD

**Issue by ikennar** [skia4delphi/skia4delphi#58] opened 2022-02-20 15:29 UTC
Build FAILED.

"E:\Embarcadero\Skia4Delphi\Packages\RAD Studio 10.3 Rio\Skia.Package.RTL.dproj" (default target) (1) ->
  E:\Embarcadero\Skia4Delphi\Packages\RAD Studio 10.3 Rio\Skia.Package.RTL.dproj : error MSB4040: There is no target in the project.

**Comment by viniciusfbb** [comment] 2022-02-20 15:49
Duplicate of #56

Hi @ikennar, thank you very much for reporting the issue.

This issue has been reported previously. It's a RAD Studio 10.3 Rio bug, in the rsvars.bat file. You can easily fix it. After that, the installer will work correctly. Learn how to fix the file rsvars.bat: https://www.tmssoftware.com/site/blog.asp?post=507

**Closed by viniciusfbb** 2022-02-20 15:49 UTC

**Comment by ikennar** [comment] 2022-02-20 16:17
Thank you.. the issue was resolved.
