### ISSUE TITLE
Right to left input in TEdit when controltype is not platform.

### ISSUE THREAD

**Issue by a-nouri** [skia4delphi/skia4delphi#106] opened 2022-05-04 17:39 UTC
Input Right to left text is not correct. there are issue in fmx algoritm.
many thanks to superb skia4delphi.

**Comment by viniciusfbb** [comment] 2022-05-04 20:21
Hi, thank you very much for reporting the issue!

Well, full support for RTL languages in input text controls (TEdit, TMemo, ...) depends on two issues:

1) A TTextLayout that supports RTL: renderer capable of drawing the texts. (Skia4Delphi implements this, so controls like TLabel support RTL)

2) Adapt the iterations between the user and the control: TEdit and TMemo must be able, for example, to correctly position the caret as the user writes a text, treating the case of the LTR and the case of the RTL. There are several adaptations that must be made in FMX.Edit.Style.pas and FMX.Memo.Style.pas, by Embarcadero.

I even commented it in an issue:

![image](https://user-images.githubusercontent.com/11139086/166802607-d9355dae-3933-4998-8107-fb69b1c82d89.png)
https://quality.embarcadero.com/browse/RSP-36975

What we should do is create an issue in the quality center asking for these corrections in FMX.Edit.Style.pas and FMX.Memo.Style.pas and ask people to vote...

**Comment by ariopax** [comment] 2022-05-08 18:16
Please make it possible.
The feature for right-to-left languages,is necessary for right to left language Delphi developer.

**Comment by viniciusfbb** [comment] 2022-08-18 21:11
Officially this is not a problem with the Skia4Delphi library, because as I said the problem is in the TEdit and TMemo code, which were not made to support RightToLeft and in fact it is one of the most problematic codes in FMX, there are dozens of problems that are not even related to the RTL and would need to be rewritten. Today, using TEdit and TMemo with ControlType=Platform is the best thing to do.

For these reasons, I will close this issue. However, I will continue to fight with the Embarcadero team to solve this as soon as possible, because with the resources Skia makes available, it is possible to correct the entire text editing system.

**Closed by viniciusfbb** 2022-08-18 21:11 UTC
