### ISSUE TITLE
Cannot Open Lottie File in skAnimatedImage

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#161] opened 2022-10-04 02:45 UTC
Nothing happens though I've verified that it's a valid lottie file by uploading it to apps.lottiefiles.com... here's the link.

https://app.lottiefiles.com/share/4cd64609-b1c4-4343-9b1e-ff56aca7b1d8

and I've attached the JSON...

[time point bounce.zip](https://github.com/skia4delphi/skia4delphi/files/9702376/time.point.bounce.zip)

Any guidance you can give me would be great...!

**Comment by viniciusfbb** [comment] 2022-10-04 20:12
Hi!

In Adobe After Effects, with the Bodymovin plugin, you can view lotties with two different libs, Lottie Web (Airbnb, in javascript) and Skottie (Skia, C++).
I opened this lottie and see the result:

In the Browser library (Airbnb lottie web, left) it worked but in Skottie (Skia, right) it didn't.

https://user-images.githubusercontent.com/11139086/193916805-49859672-d34f-4bae-a482-f41407229e24.mp4

As the issue is not related to our code I will close this topic, but I advise you to open the issue on the Skia bug page: https://bugs.chromium.org/p/skia/issues/list?q=skottie&can= two

**Closed by viniciusfbb** 2022-10-04 20:12 UTC

**Comment by TheOriginalBytePlayer** [comment] 2022-10-04 20:26
Okay, thanks for the effort.  I've posted the bug report on the skia site as you suggested.
