### ISSUE TITLE
Error compiling for RAD Studio 11.0 Alexandria 

### ISSUE THREAD

**Issue by HBenzaoui** [skia4delphi/skia4delphi#47] opened 2022-02-15 23:56 UTC
_Error compiling for RAD Studio 11.0 Alexandria - Skia.Package.RTL.dproj - Win21 (code1)._

This message was shown when the installation of skia4delphi finished

![Screenshot 2022-02-16 005511](https://user-images.githubusercontent.com/8946252/154169879-5912fa7c-e844-4670-b279-672e535c3db1.png)

Build.Logs.txt

> Microsoft (R) Build Engine version 4.8.4084.0
> [Microsoft .NET Framework, version 4.0.30319.42000]
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 16-02-22 12:59:42 AM.
> Project "C:\Users\hamza\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" on node 1 (default targets).
> C:\Users\hamza\AppData\Roaming\Embarcadero\BDS\22.0\environment.proj(5,9): error MSB5016: The name "asl.log" contains an invalid character ".". [C:\Users\hamza\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj]
> Done Building Project "C:\Users\hamza\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" (default targets) -- FAILED.
> 
> Build FAILED.
> 
> "C:\Users\hamza\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" (default target) (1) ->
>   C:\Users\hamza\AppData\Roaming\Embarcadero\BDS\22.0\environment.proj(5,9): error MSB5016: The name "asl.log" contains an invalid character ".". [C:\Users\hamza\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.32
>

**Comment by viniciusfbb** [comment] 2022-02-16 01:32
Duplicate of #39

**Closed by viniciusfbb** 2022-02-16 01:32 UTC

**Comment by viniciusfbb** [comment] 2022-02-16 01:47
Hi @HBenzaoui, thank you to report the problem. This issue has already been reported. Tomorrow we will release a fix.

**Comment by HBenzaoui** [comment] 2022-02-16 02:19
> Hi @HBenzaoui, thank you to report the problem. This issue has already been reported. Tomorrow we will release a fix.

Thanks a lot for the amazing work! Gool luck
