### ISSUE TITLE
Flickering when TForm.FullScreen is True and GlobalUseSkiaRasterWhenAvailable is False 

### ISSUE THREAD

**Issue by salvadordf** [skia4delphi/skia4delphi#127] opened 2022-06-27 16:04 UTC
Hi,

I'm testing some applications that set TForm.FullScreen to True and I added these lines to the DPR file : 
`  GlobalUseMetal := True;  GlobalUseSkia := True;  GlobalUseSkiaRasterWhenAvailable := False;`

Whe the application tries to show a popup menu it flickers and the menu is not always appearing.

I tested this on Windows 10 with a fully updated Delphi 11.1 Pro and Skia4Delphi 3.4.0

Steps to reproduce this issue :

- Create a FireMonkey application
- Drop a button to the form
- Use the OnClick event of the button and add this code :  "close;"
- Drop a TPanel and a TPopupMenu.
- Add some items to the popup menu and leave the default properties for them.
- Assign the TPopupMenu to the TPanel.Popupmenu
- Set the FullScreen property of the main form to TRUE.
- Run the application.
- Right click on the panel and the application flickers. The popup menu sometimes works correctly but sometimes appears briefly and then it disappears.
- Click on the button to close the application.

In other full screen applications with more controls and some dialogs the flickering seems to happen more frequently when the focused control changes or some dialog appear on the screen.

All these issues disappear when GlobalUseSkiaRasterWhenAvailable is set to TRUE.

**Comment by tempraturbo** [comment] 2023-01-27 20:10
When TForm.FullScreen is true and GlobalUseSkiaRasterWhenAvailable is false the TComboBox objects do not show items when clicked.

- Create a FireMonkey application;
- Enable Skia;
- Add "GlobalUseSkiaRasterWhenAvailable := false" to project source;
- Change the main form FullScreen property to true;
- Drop a combobox to the form and insert some itens;
- Run the project;
- The combobox will not show the itens when clicked.

Also, the application performance is very poor (huge frame drops) when TForm.FulScreen is true and Skia is enabled (no matter if the GlobalUseSkiaRasterWhenAvailable  is true or false);

**Comment by viniciusfbb** [comment] 2023-03-20 17:26
Fixed in our new release [v5.0.0](https://github.com/skia4delphi/skia4delphi/releases)

**Closed by viniciusfbb** 2023-03-20 17:26 UTC
Labels: OS: Windows, Type: Bug, Area: FMX Render

**Comment by zhyhero** [comment] 2023-10-28 00:42
Hello  Team ......
    When Skia4Delphi Fmx application run on WIndows 7 (x86), the application was building by Delphi 11.3,Skia4delphi 6.0.0 beta 5 and windows 11 x64 ,Skia enabled,
    if set 
         GlobalUseSkiaRasterWhenAvailable := False; 
         Form.FullScreen:=true;
    then
         all "popup like" controls or forms, like popupmenu,combobox,colorcombobox,"Showmessage()","new form"....... ,**executed invisible but clickable**……

    What can I do to fix that ?
   
   There was a "bypass", a fake fullscreen, 
        Form.BorderStyle:=TFmxFormBorderStyle.None;
        Form.FormStyle := TFormStyle.StayOnTop;
        Form.Width:=trunc(Screen.width)-2;
        Form.Height:=trunc(Scren.height)-2;
        Form.left:=1; Form.Top:=1;

    Is Skia4Delphi will keep tracking on windows 7 ?
    And  what is  the  min version number of OpenGL lib  that Skia/Skia4delphi support ?

    At last , My English is terrible.......

**Comment by viniciusfbb** [comment] 2023-10-28 11:38
@zhyhero This is a known issue with OpenGL due to the design implemented by Firemonkey. There's not much that can be done at the moment. However, without going into details, the issue is resolved in RAD Studio 12 with support a new driver much more modern than OpenGL.

**Comment by zhyhero** [comment] 2023-10-29 05:37
@viniciusfbb
Thank you for let me know.
