### ISSUE TITLE
FMX TBitmap and multithreading

### ISSUE THREAD

**Issue by cosina** [skia4delphi/skia4delphi#63] opened 2022-02-25 09:52 UTC
Hi<

In my FMX code TBitmap is updated form the thread which includes size change. Code is surrounded by a critical section. Unfortunately after a while I got an exception (Win32):

Code: 170. The requested resource is in use.

:77c3ec52 KERNELBASE.RaiseException + 0x62
System.SysUtils.RaiseLastOSError
:0043733c RaiseLastOSError + $C
System.SysUtils.RaiseLastOSError
Skia.FMX.Canvas.GL.TGrGlWindows.MakeCurrentContext
Skia.FMX.Canvas.GL.TGrCanvasGl.Prepare
Skia.FMX.Graphics.TGrCanvasCustom.TImageCache.Remove(325180536)
Skia.FMX.Graphics.TGrCanvasCustom.ClearCache(325180536)
Skia.FMX.Graphics.TSkCanvasCustom.DoFinalizeBitmap(325180536)
FMX.Graphics.TCanvas.FinalizeBitmap(???)
FMX.Graphics.TBitmapImage.FreeHandle
FMX.Graphics.TBitmapImage.DecreaseRefCount
FMX.Graphics.TBitmap.CreateNewReference
FMX.Graphics.TBitmap.SetSize(1536,???)
FMX.Graphics.TBitmap.SetSize(???)

As long as bitmap is allocated and modified within same thread everything seems to work properly.
Same code w/o SKIA works properly.

Kind regards,
Tomek Kosiński

**Comment by viniciusfbb** [comment] 2022-02-25 10:18
Hi @cosina, thank you very much to report the issue!

We will try to simulate and investigate the problem here.

**Comment by viniciusfbb** [comment] 2022-03-01 11:35
I was able to confirm the problem by performing the steps:
1. Create TBitmap in background thread;
2. Paint it in main;
3. Free the bitmap from the background thread.

This occurs even using critical section, as the problem is in the "make current" of opengl. We will release a fix within 2 days.

**Comment by cosina** [comment] 2022-03-03 10:15
Great! Will test ASAP

**Comment by viniciusfbb** [comment] 2022-03-03 19:58
Fixed in our new version [3.2.0](https://github.com/skia4delphi/skia4delphi/releases)

**Closed by viniciusfbb** 2022-03-03 19:58 UTC
Labels: Size: Medium, Type: Bug, Area: Canvas
