### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by BertieBuitendag** [skia4delphi/skia4delphi#52] opened 2022-02-17 06:32 UTC
Hello  I received the following error whilst attempting to install SKIA
![Skia](https://user-images.githubusercontent.com/45890771/154418603-f2b6a59f-2821-4908-9b64-c3f4fbac609a.JPG)

Microsoft (R) Build Engine version 4.8.4084.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2022/02/17 08:26:29.
Project "C:\Users\BAAK\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" on node 1 (default targets).
C:\Users\BAAK\AppData\Roaming\Embarcadero\BDS\22.0\environment.proj(44,9): error MSB5016: The name "settingsS400400C00941.ifsp" contains an invalid character ".". [C:\Users\BAAK\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj]
Done Building Project "C:\Users\BAAK\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\BAAK\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" (default target) (1) ->
  C:\Users\BAAK\AppData\Roaming\Embarcadero\BDS\22.0\environment.proj(44,9): error MSB5016: The name "settingsS400400C00941.ifsp" contains an invalid character ".". [C:\Users\BAAK\Documents\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.07

**Comment by viniciusfbb** [comment] 2022-02-17 09:30
Duplicate of #39

Hi @BertieBuitendag, thank you to report the problem. This issue has already been reported. Today we will release a fix, but for now you can do this workaround: https://github.com/skia4delphi/skia4delphi/issues/39#issuecomment-1039378582

**Closed by viniciusfbb** 2022-02-17 09:30 UTC
