### ISSUE TITLE
VCL much slower than FMX for SKSL shaders

### ISSUE THREAD

**Issue by WouterVanNifterick** [skia4delphi/skia4delphi#108] opened 2022-05-13 23:23 UTC
- I've made a VCL version of Jim McKeeth's FMX application to show SKSL shaders. Pull this to see it in action: https://github.com/jimmckeeth/SkiaSimpleShaderViewer/compare/main...WouterVanNifterick:vcl-support?expand=1

- It works, and it looks really nice!
  - But it's orders of magnitude slower than the FMX version, with the same implementation. 
  - Under VCL, some of the more complex shaders need multiple seconds to calculate a single frame, while I get a 30FPS with FMX.
  - The 64bit version seems to be a bit faster, but still much slower than FMX.

Is it possible that the VCL version does not use hardware acceleration, or why is there so much difference?

![image](https://user-images.githubusercontent.com/5777405/168400404-eb0d8049-625a-4160-9bfc-fa2e33786fcb.png)

**Comment by WouterVanNifterick** [comment] 2022-05-13 23:30
To compare, this is the same shader with FMX. FPS seems to be capped to 30.

![image](https://user-images.githubusercontent.com/5777405/168400970-5c67fbcb-2263-4aa8-a785-5ecf21462a37.png)

**Comment by viniciusfbb** [comment] 2022-05-14 03:11
Hi @WouterVanNifterick, 

The difference in performance is that one is running on the GPU and the other on the CPU (raster).

Currently Skia4Delphi controls only use the GPU in the following scenario:
- FMX project with "GlobalUseSkia := True;" and "GlobalUseSkiaRasterWhenAvailable := False;"

It is not very interesting to render via GPU in simple Vcl controls, such as TSkLabel or TSkSvg, as the raster mode delivers the same performance in most cases. The exception is specific and parallelizable drawings, such as shaders.

Because of this, we are thinking of adding a property to the TSkPaintBox/TSkAnimatedPaintBox, named EnableHardwareAcceleration, to enable the use of GPU in specific situations.

It will be a bit of work to add this feature, and there are other features to add first. That's why I haven't confirmed this feature in the next release yet.

**Comment by viniciusfbb** [comment] 2023-03-20 17:27
Fixed in our new release [v5.0.0](https://github.com/skia4delphi/skia4delphi/releases)

The TSkAnimatedPaintBox now is render by GPU.

**Closed by viniciusfbb** 2023-03-20 17:27 UTC
Labels: Size: Medium-Large, Area: Controls, Type: Enhancement
